// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/4/2025, 9:16:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/kevin/Documents/learn/fineline/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/learn/fineline/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/learn/fineline/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/learn/fineline/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/learn/fineline/frontend/plugins/**/*.{js,ts,mjs}","/Users/kevin/Documents/learn/fineline/frontend/composables/**/*.{js,ts,mjs}","/Users/kevin/Documents/learn/fineline/frontend/utils/**/*.{js,ts,mjs}","/Users/kevin/Documents/learn/fineline/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/learn/fineline/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/learn/fineline/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/learn/fineline/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;